// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxcwkxwlyjjlwzvnpwfp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4Y3dreHdseWpqbHd6dm5wd2ZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MDgwNzQsImV4cCI6MjA2Nzk4NDA3NH0.SSXEkZRBaAI4HgYIM1DyJPXIeAc00v9y5fr7ljxRZPQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});